[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = '=[SMODS "paperback" "utilities/hooks.lua"]'
pattern = '''      if rank.key == 'paperback_Apostle' then has_apostle = true end'''
position = "before"
overwrite = true
match_indent = true
payload = '''      if rank and rank.key == 'paperback_Apostle' then has_apostle = true end --SHIT'''

[[patches]]
[patches.pattern]
target = '=[SMODS "paperback" "utilities/hooks.lua"]'
pattern = '''      if rank.key ~= 'Ace' and rank.key ~= 'paperback_Apostle' and not rank.face then all_top = false end'''
position = "before"
overwrite = true
match_indent = true
payload = '''      if rank and rank.key ~= 'Ace' and rank.key ~= 'paperback_Apostle' and not rank.face then all_top = false end --FUCK'''

[[patches]]
[patches.pattern]
target = '''=[SMODS "paperback" "utilities/hooks.lua"]'''
pattern = '''local poker_hand_info_ref = G.FUNCS.get_poker_hand_info'''
position = "before"
match_indent = false
payload = '''
--HIIIIIIIIIIIIIIIIIIIIIIII
'''