[manifest]
version = "1.0.0"
dump_lua = true
priority = -2

# add a new gate for Molten Joker & Ooo! Shiny!
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif v.enhancement_gate then"
position = "before"
payload = '''
elseif v.picubeds_moltenjoker_gate then
    add = nil
    for kk, vv in pairs(G.playing_cards) do
        if SMODS.has_enhancement(vv, 'm_stone') or SMODS.has_enhancement(vv, 'm_gold') or SMODS.has_enhancement(vv, 'm_steel') then
            add = true
        end
    end
elseif v.picubeds_oooshiny_gate then
    add = nil
    for kk, vv in pairs(G.playing_cards) do
        if vv.edition then
            if vv.edition.key == 'e_polychrome' then
                add = true
            end
        end
    end 
    for kk, vv in pairs(G.jokers.cards) do
        if vv.edition then
            if vv.edition.key == 'e_polychrome' then
                add = true
            end
        end
    end      
'''
match_indent = true