[manifest]
version = "1.0.0"
dump_lua = true
priority = -2

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = """
for _, v in ipairs(G.handlist) do
if not results.top and results[v] then"""
position = "before"
payload = '''
if next(SMODS.find_card("j_picubed_mountjoker")) then
    local stone_count = 0
    for k,v in ipairs(G.hand.highlighted) do
        if SMODS.has_enhancement(v, 'm_stone') then 
            stone_count = stone_count + 1
        end
    end
    for k,v in ipairs(G.play.cards) do
        if SMODS.has_enhancement(v, 'm_stone') then 
            stone_count = stone_count + 1
        end
    end
    if stone_count >= 4 then
        local _tally = -1
        local stone_hand = nil
        for _, v in ipairs(G.handlist) do
            if G.GAME.hands[v].visible and G.GAME.hands[v].played > _tally then
                --text = v
                --scoring_hand = poker_hands[v]
                stone_hand = v
                _tally = G.GAME.hands[v].played
            end
        end
        results[stone_hand] = { SMODS.merge_lists(results["High Card"], results[stone_hand]) }
        --[[if next(SMODS.find_mod('bunco')) then --Spectrum (bunco) compat
            if stone_hand == "bunc_Spectrum Five" then
                results[stone_hand] = {SMODS.merge_lists(results["bunc_Spectrum"], results["Five of a Kind"], results["Four of a Kind"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
            elseif stone_hand == "bunc_Spectrum House" then
                results[stone_hand] = {SMODS.merge_lists(results["bunc_Spectrum"], results["Full House"], results["Flush"], results["Two Pair"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
            elseif stone_hand == "bunc_Straight Spectrum" then
                results[stone_hand] = {SMODS.merge_lists(results["bunc_Spectrum"], results["Straight"], results[stone_hand], results["High Card"])}
            end
        end
        if next(SMODS.find_mod('paperback')) then --Spectrum (paperback) compat
            if PB_UTIL.config.suits_enabled then
                if stone_hand == "paperback_Spectrum Five" then
                    results[stone_hand] = {SMODS.merge_lists(results["paperback_Spectrum"], results["Five of a Kind"], results["Four of a Kind"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
                elseif stone_hand == "paperback_Spectrum House" then
                    results[stone_hand] = {SMODS.merge_lists(results["paperback_Spectrum"], results["Full House"], results["Flush"], results["Two Pair"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
                elseif stone_hand == "paperback_Straight Spectrum" then
                    results[stone_hand] = {SMODS.merge_lists(results["paperback_Spectrum"], results["Straight"], results[stone_hand], results["High Card"])}
                end
            end
        end
        if next(SMODS.find_mod('SixSuits')) then --Spectrum (six suits) compat
            if stone_hand == "six_Spectrum Five" then
                results[stone_hand] = {SMODS.merge_lists(results["six_Spectrum"], results["Five of a Kind"], results["Four of a Kind"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
            elseif stone_hand == "six_Spectrum House" then
                results[stone_hand] = {SMODS.merge_lists(results["six_Spectrum"], results["Full House"], results["Flush"], results["Two Pair"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
            elseif stone_hand == "six_Straight Spectrum" then
                results[stone_hand] = {SMODS.merge_lists(results["six_Spectrum"], results["Straight"], results[stone_hand], results["High Card"])}
            end
        end
        if next(SMODS.find_mod("Cryptid")) then --Cryptid compat
            if Cryptid.enabled("set_cry_poker_hand_stuff") then
                if stone_hand == "cry_WholeDeck" then
                    results[stone_hand] = {SMODS.merge_lists(results["cry_Clusterfuck"], results["Straight Flush"], results["Flush"], results["Four of a Kind"], results["Full House"], results["Two Pair"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
                elseif stone_hand == "cry_UltPair" then
                    results[stone_hand] = {SMODS.merge_lists(results["Two Pair"], results["Pair"], results[stone_hand], results["High Card"])}
                end
            end
        end
        if stone_hand == "Flush Five" then --vanilla poker hands
            results[stone_hand] = {SMODS.merge_lists(results["Five of a Kind"], results["Four of a Kind"], results["Flush"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Flush House" then
            results[stone_hand] = {SMODS.merge_lists(results["Full House"], results["Flush"], results["Two Pair"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Five of a Kind" then
            results[stone_hand] = {SMODS.merge_lists(results["Four of a Kind"], results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Straight Flush" then
            print("hi!")
            results[stone_hand] = {SMODS.merge_lists(results["Straight"], results["Flush"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Four of a Kind" then
            results[stone_hand] = {SMODS.merge_lists(results["Three of a Kind"], results["Pair"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Full House" then 
            results[stone_hand] = {SMODS.merge_lists(results["Three of a Kind"], results["Two Pair"], results["Pair"], results[stone_hand], results["High Card"])}
        elseif stone_hand == "Three of a Kind" or stone_hand == "Two Pair" then
            results[stone_hand] = {SMODS.merge_lists(results["Pair"], results[stone_hand], results["High Card"])}
        end]]
    end
end'''
match_indent = true