[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "return G.P_CENTERS['p_buffoon_normal_'..(math.random(1, 2))]"
position = "before"
match_indent = true
payload = '''
if G.GAME.challenge == 'c_picubed_nostalgicrejuvinationdeck' then
    return G.P_CENTERS['p_celestial_mega_'..(math.random(1, 2))]
end
'''